package model

type DormentePJ struct {
	Id                                      int64  `json:"id"`
	Razao_social                            string `json:"razao_social"`
	Nome_fantasia                           string `json:"nome_fantasia"`
	Cnpj                                    string `json:"cnpj"`
	Agencia                                 string `json:"agencia"`
	Cnae                                    string `json:"cnae"`
	Faturamento                             string `json:"faturamento"`
	Contribuicao                            string `json:"contribuicao"`
	Inscricao_estadual                      string `json:"inscricao_estadual"`
	Telefone                                string `json:"telefone"`
	Email                                   string `json:"email"`
	Data_abertura                           string `json:"data_abertura"`
	Cep                                     string `json:"cep"`
	Endereco                                string `json:"endereco"`
	Numero                                  string `json:"numero"`
	Complemento                             string `json:"complemento"`
	Bairro                                  string `json:"bairro"`
	Cidade                                  string `json:"cidade"`
	Estado                                  string `json:"estado"`
	Representante_nome                      string `json:"representante_nome"`
	Representante_cpf                       string `json:"representante_cpf"`
	Representante_data_nascimento           string `json:"representante_data_nascimento"`
	Representante_telefone                  string `json:"representante_telefone"`
	Representante_nome_mae                  string `json:"representante_nome_mae"`
	Representante_sexo                      string `json:"representante_sexo"`
	Representante_email                     string `json:"representante_email"`
	Representante_estado_civil              string `json:"representante_estado_civil"`
	Representante_cep                       string `json:"representante_cep"`
	Representante_endereco                  string `json:"representante_endereco"`
	Representante_numero                    string `json:"representante_numero"`
	Representante_complemento               string `json:"representante_complemento"`
	Representante_bairro                    string `json:"representante_bairro"`
	Representante_cidade                    string `json:"representante_cidade"`
	Representante_estado                    string `json:"representante_estado"`
	Representante_documento                 string `json:"representante_documento"`
	Representante_data_emissao              string `json:"representante_data_emissao"`
	Representante_orgao_emissor             string `json:"representante_orgao_emissor"`
	Representante_estado_emissor            string `json:"representante_estado_emissor"`
	Datahora                                string `json:"datahora"`
	Usado                                   string `json:"usado"`
	Datahora_usado                          string `json:"datahora_usado"`
	Arquivo                                 string `json:"arquivo"`
	Aparelho                                string `json:"aparelho"`
	Permite_criacao_automatica              string `json:"permite_criacao_automatica"`
	Senha                                   string `json:"senha"`
	Imagecnpj                               string `json:"imagecnpj"`
	Imagecomprovante                        string `json:"imagecomprovante"`
	Imagecontrato                           string `json:"imagecontrato"`
	Imagecomprovante_endereco               string `json:"imagecomprovante_endereco"`
	Representante_imageself                 string `json:"representante_imageself"`
	Representante_imagedoc                  string `json:"representante_imagedoc"`
	Representante_imagedoc_verso            string `json:"representante_imagedoc_verso"`
	Representante_imagecomprovante_endereco string `json:"representante_imagecomprovante_endereco"`
	Representante                           string `json:"representante"`
	Representante_politico                  string `json:"representante_politico"`
	Representante_idoc                      string `json:"representante_idoc"`
	Representante_procuracao                string `json:"representante_procuracao"`
	Tipo_passaporte                         string `json:"tipo_passaporte"`
	Pais_emissor_passaporte                 string `json:"pais_emissor_passaporte"`
	Nacionalidade_passaporte                string `json:"nacionalidade_passaporte"`
	Naturalidade_passaporte                 string `json:"naturalidade_passaporte"`
	Validade_passaporte                     string `json:"validade_passaporte"`
	Data_hora_cadastro                      string `json:"data_hora_cadastro"`
	Concluir                                string `json:"concluir"`
	Codigo_indica_amigo                     string `json:"codigo_indica_amigo"`
	Proposal_kyc_id                         string `json:"proposal_kyc_id"`
	Proposal_kyc_link                       string `json:"proposal_kyc_link"`
	Proposal_kyc_status                     string `json:"proposal_kyc_status"`
	Proposal_kyc_client_code                string `json:"proposal_kyc_client_code"`
	Proposal_kyc_rejected_reason            string `json:"proposal_kyc_rejected_reason"`
	Confirmation_url                        string `json:"confirmation_url"`
}
